# Generated by Django 3.0 on 2019-12-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='Manufactorer',
            new_name='manufactorer',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='ShoeType',
            new_name='shoe_type',
        ),
    ]
